### ISSUE TITLE
Source rows Shift

### ISSUE THREAD

**Issue by eugeniodilo** [pyQode/pyQode#52] opened 2015-11-01 21:33 UTC
Add a command to shift selected source rows "n" (example  8) colums right or left .
In this way you can chage a free format souce to fixed format and viceversa.

**Comment by ColinDuquesnoy** [comment] 2015-11-01 21:37
TAB/SHIFT+TAB does not work? It should do exactly what you describe...

**Comment by ColinDuquesnoy** [comment] 2015-11-01 21:41
In OCIDE, you need to be in free format mode otherwise unindent stops at column 7. If you set free format than it will unindent by the amount of spaces you defined in the editor preferences.

**Comment by ColinDuquesnoy** [comment] 2015-11-02 07:16
Closing as duplicate of OpenCobolIDE/OpenCobolIDE#249

**Closed by ColinDuquesnoy** 2015-11-02 07:16 UTC
