### ISSUE TITLE
Problem with draggable tabs

### ISSUE THREAD

**Issue by max107** [pyQode/pyQode#31] opened 2015-04-22 11:51 UTC
![nnr3q31b3f](https://cloud.githubusercontent.com/assets/862272/7273713/080e1272-e8ff-11e4-871d-1bc923a893a1.gif)

**Comment by ColinDuquesnoy** [comment] 2015-04-22 11:59
I can reproduce it on Ubuntu. Will look into this ASAP.

**Comment by ColinDuquesnoy** [comment] 2015-04-22 15:46
Hmm actually I cannot reproduce this on linux (this was just me moving too fast while drag & dropping). But I can reproduce it on OSX (not sure why yet).

**Comment by max107** [comment] 2015-04-22 15:58
Hm... can u test this behaviour on windows os?

**Comment by ColinDuquesnoy** [comment] 2015-04-22 16:04
Works fine on windows (with PyQt4). Will try with PyQt5 later.

So far, this looks like an OSX bug. Can you try with PyQt4 on Mac?

**Comment by ColinDuquesnoy** [comment] 2015-04-22 16:28
I can confirm it also works fine on windows with PyQt5.

**Comment by max107** [comment] 2015-04-23 09:54
No, sorry, can't test with PyQt4 at current moment

**Closed** 2015-04-23 17:18 UTC
Labels: bug, Mac OSX

**Comment by ColinDuquesnoy** [comment] 2015-04-23 17:20
I've fixed it. 

The issue was related to how tabs are selected in QTabWidget. On linux and windows a tab is selected on mouse press but on OSX it only become selected on mouse release. So the wrong source tab was used to make the move and the move was canceled.

**Comment by max107** [comment] 2015-04-24 13:47
Thanks!
